In [ ]:
import pandas as pd
import numpy as np
import joblib
import csv

In [3]:
caminho_do_arquivo = '../Novo_projeto_ML/Database/Tatoeba(formal).tsv'

# Solução final combinando os parâmetros para máxima robustez
df_tatoebabruto = pd.read_csv(
    caminho_do_arquivo,
    sep='\t',                # 1. Usa tabulação como separador
    quoting=csv.QUOTE_NONE,  # 2. Ignora todas as aspas no arquivo
    on_bad_lines='skip'      # 3. Pula qualquer outra linha mal formatada
)

In [4]:
df_tatoeba = df_tatoebabruto[['English', 'Portuguese']]
df_tatoeba.head()

                  English                  Portuguese
0    Let's try something.  Vamos tentar alguma coisa!
1    Let's try something.          Vamos tentar algo!
2  I have to go to sleep.          Preciso ir dormir.
3  I have to go to sleep.        Tenho que ir dormir.
4  I have to go to sleep.             Preciso dormir.

In [5]:
caminho_do_arquivo2 = '../Novo_projeto_ML/Database/Kaggle.csv'
nomes_colunas = ['English', 'Portuguese', 'atribuicao']

df_kagglebruto = pd.read_csv(
    caminho_do_arquivo2,
    sep='\t',
    header=None,  # O ficheiro não tem uma linha de cabeçalho
    names=nomes_colunas,
    on_bad_lines='skip' # Boa prática para ignorar linhas mal formatadas
)

In [6]:
df_kaggle = df_kagglebruto[['English', 'Portuguese']]
df_kaggle.head()

  English Portuguese
0     Go.       Vai.
1     Go.        Vá.
2     Hi.        Oi.
3    Run!     Corre!
4    Run!     Corra!

In [7]:
df_final = pd.concat([df_tatoeba, df_kaggle], ignore_index=True)

In [13]:
df_final

,English,Portuguese
0,Let's try something.,Vamos tentar alguma coisa!
1,Let's try something.,Vamos tentar algo!
2,I have to go to sleep.,Preciso ir dormir.
3,I have to go to sleep.,Tenho que ir dormir.
4,I have to go to sleep.,Preciso dormir.
...,...,...
465156,I recommend contributing sentences in your own...,Recomendo que você contribua com frases em seu...
465157,A building with high ceilings and huge rooms m...,Um edifício de tetos altos e salas enormes pod...
465158,No matter how much you try to convince people ...,Não importa o quanto você tenta convencer os o...
465159,Some movies make such an impact that one never...,Alguns filmes são tão marcantes que jamais nos...
465160,A child who is a native speaker usually knows ...,Uma criança que é falante nativa geralmente sa...

In [ ]:
# df_final.to_csv('df_final.csv', index=False)